//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCafe
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLCafeEntities1 : DbContext
    {
        public QLCafeEntities1()
            : base("name=QLCafeEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Chi_Tiết_Phiếu> Chi_Tiết_Phiếu { get; set; }
        public virtual DbSet<Đăng_Nhập> Đăng_Nhập { get; set; }
        public virtual DbSet<Loại> Loại { get; set; }
        public virtual DbSet<Nhân_Viên> Nhân_Viên { get; set; }
        public virtual DbSet<Phiếu> Phiếu { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Thực_Đơn> Thực_Đơn { get; set; }
    
        public virtual int del_ban(string maban)
        {
            var mabanParameter = maban != null ?
                new ObjectParameter("maban", maban) :
                new ObjectParameter("maban", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("del_ban", mabanParameter);
        }
    
        public virtual int del_ChiTietPhieu(string maP, string maMon)
        {
            var maPParameter = maP != null ?
                new ObjectParameter("maP", maP) :
                new ObjectParameter("maP", typeof(string));
    
            var maMonParameter = maMon != null ?
                new ObjectParameter("maMon", maMon) :
                new ObjectParameter("maMon", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("del_ChiTietPhieu", maPParameter, maMonParameter);
        }
    
        public virtual int del_DangNhap(string tenDangNhap)
        {
            var tenDangNhapParameter = tenDangNhap != null ?
                new ObjectParameter("tenDangNhap", tenDangNhap) :
                new ObjectParameter("tenDangNhap", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("del_DangNhap", tenDangNhapParameter);
        }
    
        public virtual int del_Kho(string maMon)
        {
            var maMonParameter = maMon != null ?
                new ObjectParameter("maMon", maMon) :
                new ObjectParameter("maMon", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("del_Kho", maMonParameter);
        }
    
        public virtual int del_Loai(string maLoai)
        {
            var maLoaiParameter = maLoai != null ?
                new ObjectParameter("maLoai", maLoai) :
                new ObjectParameter("maLoai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("del_Loai", maLoaiParameter);
        }
    
        public virtual int del_NhanVien(string maNhanVien)
        {
            var maNhanVienParameter = maNhanVien != null ?
                new ObjectParameter("maNhanVien", maNhanVien) :
                new ObjectParameter("maNhanVien", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("del_NhanVien", maNhanVienParameter);
        }
    
        public virtual int del_Phieu(string maPhieu)
        {
            var maPhieuParameter = maPhieu != null ?
                new ObjectParameter("maPhieu", maPhieu) :
                new ObjectParameter("maPhieu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("del_Phieu", maPhieuParameter);
        }
    
        public virtual int del_ThucDon(string maMon)
        {
            var maMonParameter = maMon != null ?
                new ObjectParameter("MaMon", maMon) :
                new ObjectParameter("MaMon", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("del_ThucDon", maMonParameter);
        }
    
        public virtual int delPhieu_Main(string maPhieu, string maBan)
        {
            var maPhieuParameter = maPhieu != null ?
                new ObjectParameter("maPhieu", maPhieu) :
                new ObjectParameter("maPhieu", typeof(string));
    
            var maBanParameter = maBan != null ?
                new ObjectParameter("maBan", maBan) :
                new ObjectParameter("maBan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delPhieu_Main", maPhieuParameter, maBanParameter);
        }
    
        public virtual int get_ban(string maBan)
        {
            var maBanParameter = maBan != null ?
                new ObjectParameter("maBan", maBan) :
                new ObjectParameter("maBan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("get_ban", maBanParameter);
        }
    
        public virtual ObjectResult<get_ChiTietPhieu_Result> get_ChiTietPhieu(string maP)
        {
            var maPParameter = maP != null ?
                new ObjectParameter("MaP", maP) :
                new ObjectParameter("MaP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_ChiTietPhieu_Result>("get_ChiTietPhieu", maPParameter);
        }
    
        public virtual int get_Kho(string maMon)
        {
            var maMonParameter = maMon != null ?
                new ObjectParameter("MaMon", maMon) :
                new ObjectParameter("MaMon", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("get_Kho", maMonParameter);
        }
    
        public virtual ObjectResult<get_Loai_Result> get_Loai(string maLoai)
        {
            var maLoaiParameter = maLoai != null ?
                new ObjectParameter("MaLoai", maLoai) :
                new ObjectParameter("MaLoai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_Loai_Result>("get_Loai", maLoaiParameter);
        }
    
        public virtual ObjectResult<get_NhanVien_Result> get_NhanVien()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_NhanVien_Result>("get_NhanVien");
        }
    
        public virtual ObjectResult<get_Phieu_Result> get_Phieu(string maPhieu)
        {
            var maPhieuParameter = maPhieu != null ?
                new ObjectParameter("maPhieu", maPhieu) :
                new ObjectParameter("maPhieu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_Phieu_Result>("get_Phieu", maPhieuParameter);
        }
    
        public virtual ObjectResult<get_ThucDon_Result> get_ThucDon(string maMon)
        {
            var maMonParameter = maMon != null ?
                new ObjectParameter("maMon", maMon) :
                new ObjectParameter("maMon", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_ThucDon_Result>("get_ThucDon", maMonParameter);
        }
    
        public virtual int getall_ban()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("getall_ban");
        }
    
        public virtual ObjectResult<getall_ChiTietPhieu_Result> getall_ChiTietPhieu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getall_ChiTietPhieu_Result>("getall_ChiTietPhieu");
        }
    
        public virtual int getall_Kho()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("getall_Kho");
        }
    
        public virtual ObjectResult<getall_Loai_Result> getall_Loai()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getall_Loai_Result>("getall_Loai");
        }
    
        public virtual ObjectResult<getall_NhanVien_Result> getall_NhanVien()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getall_NhanVien_Result>("getall_NhanVien");
        }
    
        public virtual ObjectResult<getall_Phieu_Result> getall_Phieu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getall_Phieu_Result>("getall_Phieu");
        }
    
        public virtual ObjectResult<getall_ThucDon_Result> getall_ThucDon()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getall_ThucDon_Result>("getall_ThucDon");
        }
    
        public virtual ObjectResult<getCTP_Main_Result> getCTP_Main(string maphieu)
        {
            var maphieuParameter = maphieu != null ?
                new ObjectParameter("maphieu", maphieu) :
                new ObjectParameter("maphieu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getCTP_Main_Result>("getCTP_Main", maphieuParameter);
        }
    
        public virtual ObjectResult<getDangNhap_Result> getDangNhap(string tenDangNhap, string matKhau)
        {
            var tenDangNhapParameter = tenDangNhap != null ?
                new ObjectParameter("TenDangNhap", tenDangNhap) :
                new ObjectParameter("TenDangNhap", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getDangNhap_Result>("getDangNhap", tenDangNhapParameter, matKhauParameter);
        }
    
        public virtual ObjectResult<getPhieu_Main_Result> getPhieu_Main()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getPhieu_Main_Result>("getPhieu_Main");
        }
    
        public virtual ObjectResult<Nullable<decimal>> getTongTien_Main(string maPhieu, string maBan)
        {
            var maPhieuParameter = maPhieu != null ?
                new ObjectParameter("maPhieu", maPhieu) :
                new ObjectParameter("maPhieu", typeof(string));
    
            var maBanParameter = maBan != null ?
                new ObjectParameter("maBan", maBan) :
                new ObjectParameter("maBan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("getTongTien_Main", maPhieuParameter, maBanParameter);
        }
    
        public virtual ObjectResult<getThucDon_Loai_Result> getThucDon_Loai(string maLoai)
        {
            var maLoaiParameter = maLoai != null ?
                new ObjectParameter("maLoai", maLoai) :
                new ObjectParameter("maLoai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getThucDon_Loai_Result>("getThucDon_Loai", maLoaiParameter);
        }
    
        public virtual int ins_Ban(string maBan, string tenBan, Nullable<int> soluong)
        {
            var maBanParameter = maBan != null ?
                new ObjectParameter("maBan", maBan) :
                new ObjectParameter("maBan", typeof(string));
    
            var tenBanParameter = tenBan != null ?
                new ObjectParameter("tenBan", tenBan) :
                new ObjectParameter("tenBan", typeof(string));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ins_Ban", maBanParameter, tenBanParameter, soluongParameter);
        }
    
        public virtual int ins_CTP(string maPhieu, string maMon, string tenMon, Nullable<int> soluong)
        {
            var maPhieuParameter = maPhieu != null ?
                new ObjectParameter("maPhieu", maPhieu) :
                new ObjectParameter("maPhieu", typeof(string));
    
            var maMonParameter = maMon != null ?
                new ObjectParameter("maMon", maMon) :
                new ObjectParameter("maMon", typeof(string));
    
            var tenMonParameter = tenMon != null ?
                new ObjectParameter("tenMon", tenMon) :
                new ObjectParameter("tenMon", typeof(string));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ins_CTP", maPhieuParameter, maMonParameter, tenMonParameter, soluongParameter);
        }
    
        public virtual int ins_DangNhap(string maNV, string tenDangNhap, string matKhau, string quyen)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("maNV", maNV) :
                new ObjectParameter("maNV", typeof(string));
    
            var tenDangNhapParameter = tenDangNhap != null ?
                new ObjectParameter("TenDangNhap", tenDangNhap) :
                new ObjectParameter("TenDangNhap", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            var quyenParameter = quyen != null ?
                new ObjectParameter("quyen", quyen) :
                new ObjectParameter("quyen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ins_DangNhap", maNVParameter, tenDangNhapParameter, matKhauParameter, quyenParameter);
        }
    
        public virtual int ins_Kho(string maMon, string tenMon, Nullable<int> soluong, string dVT)
        {
            var maMonParameter = maMon != null ?
                new ObjectParameter("maMon", maMon) :
                new ObjectParameter("maMon", typeof(string));
    
            var tenMonParameter = tenMon != null ?
                new ObjectParameter("tenMon", tenMon) :
                new ObjectParameter("tenMon", typeof(string));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            var dVTParameter = dVT != null ?
                new ObjectParameter("DVT", dVT) :
                new ObjectParameter("DVT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ins_Kho", maMonParameter, tenMonParameter, soluongParameter, dVTParameter);
        }
    
        public virtual int ins_loai(string maloai, string tenloai)
        {
            var maloaiParameter = maloai != null ?
                new ObjectParameter("maloai", maloai) :
                new ObjectParameter("maloai", typeof(string));
    
            var tenloaiParameter = tenloai != null ?
                new ObjectParameter("tenloai", tenloai) :
                new ObjectParameter("tenloai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ins_loai", maloaiParameter, tenloaiParameter);
        }
    
        public virtual int ins_NhanVien(string maNV, string hoten, string diachi, Nullable<int> sdt, Nullable<bool> gioitinh, Nullable<decimal> luong)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("maNV", maNV) :
                new ObjectParameter("maNV", typeof(string));
    
            var hotenParameter = hoten != null ?
                new ObjectParameter("hoten", hoten) :
                new ObjectParameter("hoten", typeof(string));
    
            var diachiParameter = diachi != null ?
                new ObjectParameter("diachi", diachi) :
                new ObjectParameter("diachi", typeof(string));
    
            var sdtParameter = sdt.HasValue ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(int));
    
            var gioitinhParameter = gioitinh.HasValue ?
                new ObjectParameter("gioitinh", gioitinh) :
                new ObjectParameter("gioitinh", typeof(bool));
    
            var luongParameter = luong.HasValue ?
                new ObjectParameter("luong", luong) :
                new ObjectParameter("luong", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ins_NhanVien", maNVParameter, hotenParameter, diachiParameter, sdtParameter, gioitinhParameter, luongParameter);
        }
    
        public virtual int ins_Phieu(string maP, string maBan)
        {
            var maPParameter = maP != null ?
                new ObjectParameter("maP", maP) :
                new ObjectParameter("maP", typeof(string));
    
            var maBanParameter = maBan != null ?
                new ObjectParameter("maBan", maBan) :
                new ObjectParameter("maBan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ins_Phieu", maPParameter, maBanParameter);
        }
    
        public virtual int ins_ThucDon(string maMon, string tenMon, string maLoai, string dVT, Nullable<decimal> dongia)
        {
            var maMonParameter = maMon != null ?
                new ObjectParameter("maMon", maMon) :
                new ObjectParameter("maMon", typeof(string));
    
            var tenMonParameter = tenMon != null ?
                new ObjectParameter("tenMon", tenMon) :
                new ObjectParameter("tenMon", typeof(string));
    
            var maLoaiParameter = maLoai != null ?
                new ObjectParameter("maLoai", maLoai) :
                new ObjectParameter("maLoai", typeof(string));
    
            var dVTParameter = dVT != null ?
                new ObjectParameter("DVT", dVT) :
                new ObjectParameter("DVT", typeof(string));
    
            var dongiaParameter = dongia.HasValue ?
                new ObjectParameter("dongia", dongia) :
                new ObjectParameter("dongia", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ins_ThucDon", maMonParameter, tenMonParameter, maLoaiParameter, dVTParameter, dongiaParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<ThongKeNgay_TheoMon_Result> ThongKeNgay_TheoMon(string tenmon)
        {
            var tenmonParameter = tenmon != null ?
                new ObjectParameter("tenmon", tenmon) :
                new ObjectParameter("tenmon", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThongKeNgay_TheoMon_Result>("ThongKeNgay_TheoMon", tenmonParameter);
        }
    
        public virtual ObjectResult<ThongKeTheoMon_Result> ThongKeTheoMon()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThongKeTheoMon_Result>("ThongKeTheoMon");
        }
    
        public virtual ObjectResult<ThongKeTheoMon_TheoNgay_Result> ThongKeTheoMon_TheoNgay(Nullable<System.DateTime> ngaytao)
        {
            var ngaytaoParameter = ngaytao.HasValue ?
                new ObjectParameter("ngaytao", ngaytao) :
                new ObjectParameter("ngaytao", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThongKeTheoMon_TheoNgay_Result>("ThongKeTheoMon_TheoNgay", ngaytaoParameter);
        }
    
        public virtual ObjectResult<ThongKeTheoNgay_Result> ThongKeTheoNgay()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThongKeTheoNgay_Result>("ThongKeTheoNgay");
        }
    
        public virtual int upd_Ban(string maBan, string tenBan, Nullable<int> songuoi)
        {
            var maBanParameter = maBan != null ?
                new ObjectParameter("maBan", maBan) :
                new ObjectParameter("maBan", typeof(string));
    
            var tenBanParameter = tenBan != null ?
                new ObjectParameter("tenBan", tenBan) :
                new ObjectParameter("tenBan", typeof(string));
    
            var songuoiParameter = songuoi.HasValue ?
                new ObjectParameter("songuoi", songuoi) :
                new ObjectParameter("songuoi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("upd_Ban", maBanParameter, tenBanParameter, songuoiParameter);
        }
    
        public virtual int upd_CTP(string maPhieu, string maMon, string tenMon, Nullable<int> soluong, Nullable<decimal> thanhtien)
        {
            var maPhieuParameter = maPhieu != null ?
                new ObjectParameter("maPhieu", maPhieu) :
                new ObjectParameter("maPhieu", typeof(string));
    
            var maMonParameter = maMon != null ?
                new ObjectParameter("maMon", maMon) :
                new ObjectParameter("maMon", typeof(string));
    
            var tenMonParameter = tenMon != null ?
                new ObjectParameter("tenMon", tenMon) :
                new ObjectParameter("tenMon", typeof(string));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            var thanhtienParameter = thanhtien.HasValue ?
                new ObjectParameter("thanhtien", thanhtien) :
                new ObjectParameter("thanhtien", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("upd_CTP", maPhieuParameter, maMonParameter, tenMonParameter, soluongParameter, thanhtienParameter);
        }
    
        public virtual int upd_Kho(string maMon, string tenMon, Nullable<int> soluong, string dVT)
        {
            var maMonParameter = maMon != null ?
                new ObjectParameter("maMon", maMon) :
                new ObjectParameter("maMon", typeof(string));
    
            var tenMonParameter = tenMon != null ?
                new ObjectParameter("tenMon", tenMon) :
                new ObjectParameter("tenMon", typeof(string));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            var dVTParameter = dVT != null ?
                new ObjectParameter("DVT", dVT) :
                new ObjectParameter("DVT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("upd_Kho", maMonParameter, tenMonParameter, soluongParameter, dVTParameter);
        }
    
        public virtual int upd_Loai(string maLoai, string tenLoai)
        {
            var maLoaiParameter = maLoai != null ?
                new ObjectParameter("maLoai", maLoai) :
                new ObjectParameter("maLoai", typeof(string));
    
            var tenLoaiParameter = tenLoai != null ?
                new ObjectParameter("tenLoai", tenLoai) :
                new ObjectParameter("tenLoai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("upd_Loai", maLoaiParameter, tenLoaiParameter);
        }
    
        public virtual int upd_NhanVien(string maNV, string hoten, string diachi, Nullable<int> sDT, Nullable<bool> gioitinh, Nullable<decimal> luong)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("maNV", maNV) :
                new ObjectParameter("maNV", typeof(string));
    
            var hotenParameter = hoten != null ?
                new ObjectParameter("hoten", hoten) :
                new ObjectParameter("hoten", typeof(string));
    
            var diachiParameter = diachi != null ?
                new ObjectParameter("diachi", diachi) :
                new ObjectParameter("diachi", typeof(string));
    
            var sDTParameter = sDT.HasValue ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(int));
    
            var gioitinhParameter = gioitinh.HasValue ?
                new ObjectParameter("gioitinh", gioitinh) :
                new ObjectParameter("gioitinh", typeof(bool));
    
            var luongParameter = luong.HasValue ?
                new ObjectParameter("luong", luong) :
                new ObjectParameter("luong", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("upd_NhanVien", maNVParameter, hotenParameter, diachiParameter, sDTParameter, gioitinhParameter, luongParameter);
        }
    
        public virtual int upd_Phieu(string maPhieu, string maBan)
        {
            var maPhieuParameter = maPhieu != null ?
                new ObjectParameter("maPhieu", maPhieu) :
                new ObjectParameter("maPhieu", typeof(string));
    
            var maBanParameter = maBan != null ?
                new ObjectParameter("maBan", maBan) :
                new ObjectParameter("maBan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("upd_Phieu", maPhieuParameter, maBanParameter);
        }
    
        public virtual int upd_ThucDon(string maMon, string tenmon, string maLoai, string dVT, Nullable<decimal> dongia)
        {
            var maMonParameter = maMon != null ?
                new ObjectParameter("maMon", maMon) :
                new ObjectParameter("maMon", typeof(string));
    
            var tenmonParameter = tenmon != null ?
                new ObjectParameter("tenmon", tenmon) :
                new ObjectParameter("tenmon", typeof(string));
    
            var maLoaiParameter = maLoai != null ?
                new ObjectParameter("maLoai", maLoai) :
                new ObjectParameter("maLoai", typeof(string));
    
            var dVTParameter = dVT != null ?
                new ObjectParameter("DVT", dVT) :
                new ObjectParameter("DVT", typeof(string));
    
            var dongiaParameter = dongia.HasValue ?
                new ObjectParameter("dongia", dongia) :
                new ObjectParameter("dongia", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("upd_ThucDon", maMonParameter, tenmonParameter, maLoaiParameter, dVTParameter, dongiaParameter);
        }
    
        public virtual ObjectResult<getbetween_1_Result> getbetween_1(Nullable<System.DateTime> ngaydau, Nullable<System.DateTime> ngaycuoi)
        {
            var ngaydauParameter = ngaydau.HasValue ?
                new ObjectParameter("ngaydau", ngaydau) :
                new ObjectParameter("ngaydau", typeof(System.DateTime));
    
            var ngaycuoiParameter = ngaycuoi.HasValue ?
                new ObjectParameter("ngaycuoi", ngaycuoi) :
                new ObjectParameter("ngaycuoi", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getbetween_1_Result>("getbetween_1", ngaydauParameter, ngaycuoiParameter);
        }
    
        public virtual ObjectResult<getbetween_2_Result> getbetween_2(Nullable<System.DateTime> ngaydau, Nullable<System.DateTime> ngaycuoi)
        {
            var ngaydauParameter = ngaydau.HasValue ?
                new ObjectParameter("ngaydau", ngaydau) :
                new ObjectParameter("ngaydau", typeof(System.DateTime));
    
            var ngaycuoiParameter = ngaycuoi.HasValue ?
                new ObjectParameter("ngaycuoi", ngaycuoi) :
                new ObjectParameter("ngaycuoi", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getbetween_2_Result>("getbetween_2", ngaydauParameter, ngaycuoiParameter);
        }
    }
}
