//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCafe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nhân_Viên
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nhân_Viên()
        {
            this.Đăng_Nhập = new HashSet<Đăng_Nhập>();
        }
    
        public string MaNV { get; set; }
        public string HoTen { get; set; }
        public string DiaChi { get; set; }
        public string SĐT { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public Nullable<decimal> Luong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Đăng_Nhập> Đăng_Nhập { get; set; }
    }
}
