//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCafe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phiếu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phiếu()
        {
            this.Chi_Tiết_Phiếu = new HashSet<Chi_Tiết_Phiếu>();
        }
    
        public string MaPhieu { get; set; }
        public string MaBan { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<bool> TinhTien { get; set; }
        public Nullable<decimal> TongTien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chi_Tiết_Phiếu> Chi_Tiết_Phiếu { get; set; }
    }
}
