//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCafe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thực_Đơn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Thực_Đơn()
        {
            this.Chi_Tiết_Phiếu = new HashSet<Chi_Tiết_Phiếu>();
        }
    
        public string MaMon { get; set; }
        public string TenMon { get; set; }
        public string MaLoai { get; set; }
        public string DVT { get; set; }
        public Nullable<decimal> DonGia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chi_Tiết_Phiếu> Chi_Tiết_Phiếu { get; set; }
        public virtual Loại Loại { get; set; }
    }
}
